# Generated by Django 5.0.3 on 2024-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cod_property', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('guests_limit', models.IntegerField()),
                ('bath_quant', models.IntegerField()),
                ('acceptable_pets', models.BooleanField()),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
