# Generated by Django 5.0.3 on 2024-03-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AlterField(
            model_name='property',
            name='cod_property',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
